"""
Pure code rendering for the ALGORITHM rung of the reification ladder.

No I/O and no infrastructure imports — this assembles *verified* expressions into
executable Python source. It lives in the domain because "concept -> symbol ->
derivation -> code" is core to NSForge's purpose: the final rung must be reified
by a deterministic renderer, not hand-written by the agent.
"""

from __future__ import annotations


def render_python_function(
    name: str,
    description: str,
    parameters: list[dict[str, str]],
    steps: list[dict[str, str]],
    return_vars: list[str],
) -> str:
    """Assemble a Python function from verified derivation steps.

    Args:
        name: Function name (a valid identifier).
        description: One-line docstring description.
        parameters: ``[{"name", "type"?, "description"?}, ...]`` inputs.
        steps: ``[{"description", "expression", "result_var"}, ...]`` computations.
        return_vars: Names returned in the result dict.

    Returns:
        The Python source as a string. Pure — performs no computation itself.
    """
    param_str = ", ".join(f"{p['name']}: {p.get('type', 'float')}" for p in parameters)

    doc_lines = [f'    """{description}', "", "    Args:"]
    for p in parameters:
        doc_lines.append(f"        {p['name']}: {p.get('description', '')}")
    doc_lines += [
        "",
        "    Returns:",
        f"        dict with keys: {return_vars}",
        "",
        "    Note:",
        "        Generated by NSForge from a verified derivation (provenance-bound).",
        '    """',
    ]
    docstring = "\n".join(doc_lines)

    body_lines = [
        "    from sympy import cos, exp, log, pi, sin, sqrt, tan  # noqa: F401",
        "",
    ]
    for i, step in enumerate(steps, 1):
        body_lines.append(f"    # Step {i}: {step['description']}")
        body_lines.append(f"    {step['result_var']} = {step['expression']}")
        body_lines.append("")
    return_dict = ", ".join(f'"{v}": {v}' for v in return_vars)
    body_lines.append(f"    return {{{return_dict}}}")
    body = "\n".join(body_lines)

    return f"def {name}({param_str}):\n{docstring}\n{body}\n"
