"""
NPO（禁食）對口服抗生素療效影響分析
=====================================

此腳本使用 NSForge 推導的模型分析：
1. Henderson-Hasselbalch 方程式：pH 如何影響藥物離子化
2. Emax 藥效學模型：濃度如何轉化為療效

臨床情境：
- 正常進食：胃 pH ≈ 1.5-2.5
- NPO/禁食：胃 pH ≈ 3.5-5.0（胃酸分泌減少）
- 弱酸性藥物在低 pH 時非離子化比例高，吸收較好
"""

import numpy as np
import matplotlib.pyplot as plt


def calculate_npo_antibiotic_effect(
    pH: float, pKa: float, D: float, F_base: float, Vd: float,
    E_0: float, E_max: float, EC_50: float, n: float
) -> dict:
    """Calculate antibiotic effect considering pH-dependent absorption.
    
    Models how NPO (fasting) affects oral antibiotic efficacy through 
    changes in gastric pH and drug ionization.

    Args:
        pH: Gastric pH (normal fed: 1.5-2.5, NPO/fasting: 3.5-5.0)
        pKa: Drug pKa value (e.g., ciprofloxacin ~6.1, amoxicillin ~2.4)
        D: Administered dose in mg
        F_base: Baseline bioavailability (0-1)
        Vd: Volume of distribution in L
        E_0: Baseline effect (e.g., baseline bacterial count)
        E_max: Maximum effect achievable
        EC_50: Concentration for 50% max effect (mg/L)
        n: Hill coefficient (typically 1-4)

    Returns:
        dict with keys: ['f_nonionized', 'C_effective', 'E']

    Note:
        Generated by NSForge derivation workflow.
        Based on Henderson-Hasselbalch equation and Sigmoid Emax model.
    """
    # Step 1: Calculate fraction of non-ionized (absorbable) drug
    # Henderson-Hasselbalch: f = 1 / (1 + 10^(pH-pKa)) for weak acids
    f_nonionized = 1 / (1 + 10**(pH - pKa))

    # Step 2: Calculate effective plasma concentration
    # C = F * D / Vd, where F is affected by ionization
    C_effective = F_base * f_nonionized * D / Vd

    # Step 3: Calculate pharmacological effect using Emax model
    # E = E_0 + (E_max * C^n) / (EC_50^n + C^n)
    E = E_0 + (E_max * C_effective**n) / (EC_50**n + C_effective**n)

    return {
        "f_nonionized": f_nonionized,
        "C_effective": C_effective,
        "E": E
    }


def analyze_npo_impact():
    """
    分析 NPO 對常見口服抗生素的影響
    """
    # 常見抗生素參數
    antibiotics = {
        "Amoxicillin": {
            "pKa": 2.4,      # 弱酸性
            "D": 500,        # 500 mg
            "F_base": 0.8,   # 80% baseline bioavailability
            "Vd": 20,        # 20 L
            "EC_50": 2.0,    # 2 mg/L for typical bacteria
            "n": 1.5,        # Hill coefficient
        },
        "Ciprofloxacin": {
            "pKa": 6.1,      # 較弱酸性
            "D": 500,        # 500 mg
            "F_base": 0.7,   # 70% baseline bioavailability
            "Vd": 140,       # 140 L (large Vd)
            "EC_50": 0.5,    # 0.5 mg/L
            "n": 2.0,
        },
        "Levofloxacin": {
            "pKa": 5.5,
            "D": 500,
            "F_base": 0.99,  # Very high bioavailability
            "Vd": 100,
            "EC_50": 1.0,
            "n": 1.8,
        },
    }
    
    # 模擬參數
    E_0 = 0        # 基線效果（無殺菌）
    E_max = 100    # 最大殺菌效果（%）
    
    # pH 範圍
    pH_fed = 2.0       # 進食後胃 pH
    pH_npo = 4.5       # NPO 胃 pH
    pH_range = np.linspace(1.0, 7.0, 100)
    
    print("=" * 70)
    print("NPO（禁食）對口服抗生素療效影響分析")
    print("=" * 70)
    print()
    
    results = {}
    
    for name, params in antibiotics.items():
        print(f"\n【{name}】(pKa = {params['pKa']})")
        print("-" * 50)
        
        # 計算進食狀態
        fed_result = calculate_npo_antibiotic_effect(
            pH=pH_fed,
            pKa=params["pKa"],
            D=params["D"],
            F_base=params["F_base"],
            Vd=params["Vd"],
            E_0=E_0,
            E_max=E_max,
            EC_50=params["EC_50"],
            n=params["n"]
        )
        
        # 計算 NPO 狀態
        npo_result = calculate_npo_antibiotic_effect(
            pH=pH_npo,
            pKa=params["pKa"],
            D=params["D"],
            F_base=params["F_base"],
            Vd=params["Vd"],
            E_0=E_0,
            E_max=E_max,
            EC_50=params["EC_50"],
            n=params["n"]
        )
        
        # 計算不同 pH 下的效果曲線
        effects = []
        for ph in pH_range:
            r = calculate_npo_antibiotic_effect(
                pH=ph,
                pKa=params["pKa"],
                D=params["D"],
                F_base=params["F_base"],
                Vd=params["Vd"],
                E_0=E_0,
                E_max=E_max,
                EC_50=params["EC_50"],
                n=params["n"]
            )
            effects.append(r["E"])
        
        results[name] = {
            "fed": fed_result,
            "npo": npo_result,
            "pH_range": pH_range,
            "effects": effects
        }
        
        # 報告
        print(f"  進食狀態 (pH={pH_fed}):")
        print(f"    - 非離子化比例: {fed_result['f_nonionized']:.1%}")
        print(f"    - 有效血漿濃度: {fed_result['C_effective']:.2f} mg/L")
        print(f"    - 殺菌效果: {fed_result['E']:.1f}%")
        
        print(f"  NPO 狀態 (pH={pH_npo}):")
        print(f"    - 非離子化比例: {npo_result['f_nonionized']:.1%}")
        print(f"    - 有效血漿濃度: {npo_result['C_effective']:.2f} mg/L")
        print(f"    - 殺菌效果: {npo_result['E']:.1f}%")
        
        # 療效下降百分比
        effect_reduction = (fed_result['E'] - npo_result['E']) / fed_result['E'] * 100
        print(f"  ⚠️  NPO 導致療效下降: {effect_reduction:.1f}%")
    
    return results


def plot_results(results):
    """繪製 pH-效果關係圖"""
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    colors = {"Amoxicillin": "blue", "Ciprofloxacin": "red", "Levofloxacin": "green"}
    
    for i, (name, data) in enumerate(results.items()):
        ax = axes[i]
        ax.plot(data["pH_range"], data["effects"], color=colors[name], linewidth=2)
        ax.axvline(x=2.0, color="gray", linestyle="--", alpha=0.7, label="Fed pH")
        ax.axvline(x=4.5, color="orange", linestyle="--", alpha=0.7, label="NPO pH")
        ax.scatter([2.0], [data["fed"]["E"]], color="green", s=100, zorder=5, label="Fed")
        ax.scatter([4.5], [data["npo"]["E"]], color="red", s=100, zorder=5, label="NPO")
        
        ax.set_xlabel("Gastric pH", fontsize=12)
        ax.set_ylabel("Bactericidal Effect (%)", fontsize=12)
        ax.set_title(f"{name} (pKa={results[name]['fed']['f_nonionized']:.2f})", fontsize=14)
        ax.legend(loc="upper right")
        ax.grid(True, alpha=0.3)
        ax.set_xlim(1, 7)
        ax.set_ylim(0, 105)
    
    plt.suptitle("NPO Impact on Oral Antibiotic Efficacy", fontsize=16, y=1.02)
    plt.tight_layout()
    plt.savefig("npo_antibiotic_analysis.png", dpi=150, bbox_inches="tight")
    print("\n圖表已保存至 npo_antibiotic_analysis.png")


def clinical_recommendations():
    """臨床建議"""
    print("\n" + "=" * 70)
    print("臨床建議")
    print("=" * 70)
    print("""
1. 【Amoxicillin (pKa=2.4)】
   - 弱酸性藥物，在低 pH 環境吸收最佳
   - NPO 時胃 pH 升高會顯著降低吸收
   - 建議：可與少量酸性飲料服用，或改用 IV 給藥

2. 【Ciprofloxacin (pKa=6.1)】
   - pKa 較高，pH 變化影響相對較小
   - 但仍受金屬離子螯合影響
   - 建議：避免與制酸劑同服，NPO 時影響較小

3. 【Levofloxacin (pKa=5.5)】
   - 生體可用率本身極高 (>99%)
   - pH 變化影響相對較小
   - 建議：NPO 患者可優先選用

4. 【一般原則】
   - 對於需要 NPO 的重症患者，考慮改用 IV 抗生素
   - 若必須口服，選擇 pKa 較高或生體可用率較高的藥物
   - 監測臨床療效，必要時調整劑量
""")


if __name__ == "__main__":
    # 執行分析
    results = analyze_npo_impact()
    
    # 臨床建議
    clinical_recommendations()
    
    # 繪圖（如果有 matplotlib）
    try:
        plot_results(results)
    except ImportError:
        print("\n（需要 matplotlib 才能繪製圖表）")
